#+TITLE: Gradle ClassWorlds Assembly Plugin

* Summary

The Gradle ClassWorlds Assembly Plugin is a simple [[http://www.gradle.org/][Gradle]] plugin that generates a simple zipped distribution of your project, using [[http://classworlds.codehaus.org/launchusage.html][Classworlds]] as application launcher.

Extract the archive and it's ready to go! This plugin is an alternative to the [[http://www.gradle.org/docs/current/userguide/application_plugin.html][Gradle application plugin]].

Sometimes it is easier to ship your application as a simple *zip* or *tar* archive instead of bothering with a sophisticated software installer.

The generated assembly name follows the pattern =<project-name>-<project-version>.<assemblyformat>=.

Below is the standard folder structure of assemblies generated by the plugin.

: ApplicationFolder : (projectName-ProjectVersion)
: |
: --- boot: Contains the application launcher bootstrap jars
: |
: --- etc : Contains the launcher configuration
: |
: --- lib : Contains the application dependencies and build artifacts
: |
: --- bin : Contains the application launcher scripts (run.bat and run.sh)

Simplicity is exactly what this Gradle plugin provides:
 - You have an application that is launched via a main class.
 - Your application has a set of dependencies.
 - Launching the application is just a matter of having all the dependencies in the classpath and running the main method of your application entry point.
 - Create and archive and ship it!

* Installation and configuration

** Installation to your local Maven cache
*Note*: This plugin is not yet available on a hosted Maven repository.

Clone the project from GitHub and run =gradlew install=, to install the plugin into your local Maven cache.

** Integration setup

The first step consists into configuring the =buildscript= closure at the top of your Gradle build file. Then you can apply the =classworlds= plugin.

 : buildscript {
 :   repositories {
 :     maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
 :   }
 :
 :   dependencies {
 :     classpath 'com.rimerosolutions.gradle.plugins:gradle-classworlds-plugin:0.0.1-SNAPSHOT'
 :   }
 : }
 : 
 : apply plugin: 'classworlds'

** Plugin configuration
The plugin has only one required input which is the main class name of your application.

The main class name configuration is provided via the =appMainClassName= variable in a configuration block.

Configuration parameters are to be specified inside a =classworlds= block in your Gradle build file.
: classworlds {
:   // mandatory inputs
:   appMainClassName = 'com.Main'
:
:   // optional inputs
:   appLocationEnvVariableName='APP_HOME_IF_YOU_NEED_IT'
:   assemblyFileName="application"
:   assemblyFormats = ['zip', 'tar']
:   jvmOptions = '-Xms512m -Xmx1g'
:
:   doWithStagingDir = { stagingFolder ->
:     println 'Customizations, other actions here if needed'
:   }
: }

* Tasks
The plugin provides only one task called =classworlds=.

The =classworlds= task generates a zip and/or tar assembly of your project with UNIX and Windows application launchers.

Running the =classworlds= task will also trigger the =build= task to generate the project artifacts.
 : gradle classworlds

* Testing the generated distribution
Unzip the generated zip assembly which is inside your build folder to the location of your choice.

You must first set an environment variable matching the =appLocationEnvVariableName= parameter specified in your Gradle build file.

For the instructions below, we'll suppose that =appLocationEnvVariableName= is set to =YOUR_APPLICATION_ENVIRONMENT_VARIABLE=.

** Unix/Linux (bash)
: export YOUR_APPLICATION_ENVIRONMENT_VARIABLE=SOME_FOLDER_LOCATION
: sh ${YOUR_APPLICATION_ENVIRONMENT_VARIABLE}/bin/run.sh

Use =setenv= instead of =export= if you're using =csh= or =tcsh= as UNIX/Linux shell.

** MS Windows
: set YOUR_APPLICATION_ENVIRONMENT_VARIABLE=SOME_FOLDER_LOCATION
: %YOUR_APPLICATION_ENVIRONMENT_VARIABLE%/bin/run.bat

* Possible enhancements
 - Better use of Gradle inputs and outputs, still doing few manual values assignments.
 - Write more tests
